# Generated by Django 4.2 on 2023-04-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('doc_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='CNPJ')),
                ('slug', models.SlugField(blank=True, max_length=16, null=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/relatorios/')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogLineError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(blank=True, null=True, verbose_name='Referencia')),
                ('identifiy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Erro')),
                ('line', models.JSONField(blank=True, null=True, verbose_name='Linha')),
            ],
            options={
                'verbose_name': 'Erros',
                'verbose_name_plural': 'Erros',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=16, null=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('slug', models.SlugField(max_length=16, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(verbose_name='codigo da venda')),
                ('date_create', models.DateField(blank=True, null=True, verbose_name='Data da Emissão')),
                ('date_confirm', models.DateField(blank=True, null=True, verbose_name='Data da Comfirmação')),
                ('profit', models.FloatField(blank=True, default=0, null=True, verbose_name='Lucro empresa')),
                ('transfer_fee_amount', models.CharField(blank=True, max_length=128, null=True, verbose_name='Valor da Taxa')),
                ('result', models.FloatField(blank=True, default=0, null=True, verbose_name='Lucro Líquido')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Cliente')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.file', verbose_name='Arquivo')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Produto')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
